### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by ArmorDarks** [stephanmax/grunt-responsive-images-extender#12]
Hi

I'm receiving following error:

```
Warning: Path must be a string. Received [ 'build/blog/2015-10-12-example-article/index.html' ] Use --force to continue.
```

Here is my config

``` coffee
module.exports = ->
  @config 'responsive_images_extender',
    thumbnails:
      files: [
        expand: true
        cwd: 'build/'
        src: ['**/*.{html,htm,php}']
        dest: 'test/'
      ]
```

It's quite same, as the one in `readme.md`.

Versions:

```
grunt-cli v0.1.13
grunt v1.0.1
node v6.2.0
```

Here is full log with message:

![conemu_2016-08-04_22-36-52](https://cloud.githubusercontent.com/assets/4460311/17415808/fbf5aa24-5a93-11e6-9dbf-80dfd1d1f4ef.png)

Am I missing something obvious?

**Comment by phofm** [comment]
Hi

I have the same issue on one machine but not on the other.

The only difference I can see is that the machine it isn’t working on has different dependencies:

<pre>
├─┬ grunt-responsive-images-extender@2.0.1
│ ├─┬ cheerio@0.19.0
│ │ ├─┬ css-select@1.0.0
│ │ │ ├── boolbase@1.0.0
│ │ │ ├── css-what@1.0.0
│ │ │ ├─┬ domutils@1.4.3
│ │ │ │ └── domelementtype@1.3.0 /* only on the machine, where it’s not working */
│ │ │ └── nth-check@1.0.1
│ │ ├─┬ dom-serializer@0.1.0
│ │ │ └── domelementtype@1.1.3 /* only on the machine, where it’s not working */
│ │ ├── entities@1.1.1
│ │ ├─┬ htmlparser2@3.8.3
│ │ │ ├── domelementtype@1.3.0
│ │ │ ├── domhandler@2.3.0
│ │ │ ├── domutils@1.5.1
│ │ │ ├── entities@1.0.0
│ │ │ └─┬ readable-stream@1.1.14
│ │ │   ├── core-util-is@1.0.2
│ │ │   ├── inherits@2.0.1 /* only on the machine, where it’s not working */
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ └── lodash@3.10.1
│ └── image-size@0.3.5
</pre>

Any hints would be greatly appreciated!

**Comment by stephanmax** [comment]
Hey guys,
I'm on the road right now, but will look into this during the weekend.
Thanks for flagging,
Stephan

**Comment by phofm** [comment]
Thanks @stephanmax!

I checked the node.js versions on both machines: the one it was working on was running 5.9.0 the one it was not working on 6.3.0. After downgrading the latter to 5.12.0 it is working again. So it might be something in the change from the node 5.x-branch to the 6.x-branch?

**Comment by ArmorDarks** [comment]
This is because on Node 6.0.0 and higher `path` module accepts only `string` as input, while `grunt-responsive-images-extender` passes `array` with single value

**Comment by sjbuysse** [comment]
Is there a way to fix this? @ArmorDarks

**Comment by ArmorDarks** [comment]
It should be fixed in code, so, only via PR.

**Comment by ArmorDarks** [comment]
Hi @stephanmax 

Just thought that it worth to ping you out :)

**Comment by errol1989** [comment]
Dear S, by reviewing your JS code,  I think the function named parseAndExtendImg need a string as the parameter, while f. src is an Array. Maybe a simple forEach will fix it. Hope your update because this is a really aewsome plugin!

**Comment by mau-ferrusca** [comment]
So, is there a workaround, @ArmorDarks? I'm stuck with the "Path must be string" error too.

Thanks.

**Comment by mau-ferrusca** [comment]
Has anyone been able to make this plugin work with higher versions of Node? I tried downgrading using nvmw but it's not as easy as it should've been.

**Comment by stephanmax** [comment]
Hi guys,
It's been a while, sorry for that and more importantly thanks for your patience.
This bug has been fixed, the plugin now also accounts for multi-src files and I added a test to make sure things are going down smoothly.
Let me know if something does not work. Until then I consider this matter closed. Thanks all for contributing and your nice words about this plugin.
Stephan

**Comment by mau-ferrusca** [comment]
It's fixed in version 2.0.1? I got if working downgrading to Node 4. Should we upgrade the plugin for your fix to work then?

Thanks!

**Comment by stephanmax** [comment]
Hi @mau-ferrusca, it's been fixed in version 3.0.0 and is good to go for Node version >=6. Upgrading to latest Node and plugin and you should be good to go.

**Comment by mau-ferrusca** [comment]
Thanks for the clarification.

I asked because I [ran `npm update`](https://docs.npmjs.com/getting-started/updating-local-packages) but the plugin is stil v 2.0.1

**Comment by stephanmax** [comment]
Weird, thanks for flagging. Could you try again? It should have been updated in the npm registry by now.

**Comment by mau-ferrusca** [comment]
Perfect. Got 3.0.0 now. Thank you, @stephanmax.
